version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/development/Dockerfile
    depends_on:
      - nginx
      - database
      - redis
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./docker/app/development/vhost.conf:/etc/nginx/conf.d/default.conf:ro

  database:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 54320:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  postgres:
    driver: local

networks:
  default:
    name: "${APP_SLUG}-network"
